<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AgentsSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing
        Agent::query()->delete();

        $agents = [
            // TIER 1: Basic Agents (8 agents) - $10/month
            [
                'name' => 'Customer Support Agent',
                'slug' => 'customer-support',
                'tier_id' => 1,
                'description' => 'Handles customer inquiries and FAQs',
                'long_description' => 'AI-powered customer support agent that handles routine inquiries, FAQs, and basic troubleshooting.',
                'icon_url' => '/images/agents/customer-support.png',
                'capabilities' => ['FAQ responses', 'Ticket routing', 'Basic troubleshooting'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Data Entry Agent',
                'slug' => 'data-entry',
                'tier_id' => 1,
                'description' => 'Extracts and inputs data from documents',
                'long_description' => 'Automated data entry agent that extracts information from documents and inputs it into systems.',
                'icon_url' => '/images/agents/data-entry.png',
                'capabilities' => ['OCR', 'Data extraction', 'Form filling'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Email Automation Agent',
                'slug' => 'email-automation',
                'tier_id' => 1,
                'description' => 'Automates routine email responses',
                'long_description' => 'Smart email automation agent that handles routine email responses and follow-ups.',
                'icon_url' => '/images/agents/email-automation.png',
                'capabilities' => ['Email templates', 'Auto-response', 'Follow-ups'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Simple Scheduler Agent',
                'slug' => 'simple-scheduler',
                'tier_id' => 1,
                'description' => 'Schedules appointments and meetings',
                'long_description' => 'Basic scheduling agent for appointments and meeting coordination.',
                'icon_url' => '/images/agents/scheduler.png',
                'capabilities' => ['Calendar integration', 'Appointment booking', 'Reminders'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Social Media Poster Agent',
                'slug' => 'social-media-poster',
                'tier_id' => 1,
                'description' => 'Posts content across social platforms',
                'long_description' => 'Automated social media posting agent for scheduling and publishing content.',
                'icon_url' => '/images/agents/social-media.png',
                'capabilities' => ['Multi-platform posting', 'Scheduling', 'Content formatting'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'File Organizer Agent',
                'slug' => 'file-organizer',
                'tier_id' => 1,
                'description' => 'Organizes and categorizes files',
                'long_description' => 'Intelligent file organization agent that categorizes and structures documents.',
                'icon_url' => '/images/agents/file-organizer.png',
                'capabilities' => ['Auto-categorization', 'File naming', 'Folder structure'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Form Processor Agent',
                'slug' => 'form-processor',
                'tier_id' => 1,
                'description' => 'Processes and validates forms',
                'long_description' => 'Automated form processing agent with validation and data extraction.',
                'icon_url' => '/images/agents/form-processor.png',
                'capabilities' => ['Form validation', 'Data extraction', 'Error checking'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Simple Translator Agent',
                'slug' => 'simple-translator',
                'tier_id' => 1,
                'description' => 'Translates simple text',
                'long_description' => 'Basic translation agent for simple text and phrases.',
                'icon_url' => '/images/agents/translator.png',
                'capabilities' => ['Text translation', 'Multiple languages'],
                'supported_languages' => ['en', 'ar', 'fr', 'es'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],

            // TIER 2: Professional Agents (12 agents) - $29/month
            [
                'name' => 'HR Recruitment Agent',
                'slug' => 'hr-recruitment',
                'tier_id' => 2,
                'description' => 'Screens CVs and matches candidates',
                'long_description' => 'Professional HR agent for resume screening, candidate matching, and interview scheduling.',
                'icon_url' => '/images/agents/hr-recruitment.png',
                'capabilities' => ['CV screening', 'Candidate matching', 'Interview scheduling'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'is_featured' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Content Creation Agent',
                'slug' => 'content-creation',
                'tier_id' => 2,
                'description' => 'Creates blog posts and articles',
                'long_description' => 'AI content writer for blog posts, articles, and marketing copy.',
                'icon_url' => '/images/agents/content-creation.png',
                'capabilities' => ['Blog writing', 'SEO optimization', 'Content research'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Financial Analysis Agent',
                'slug' => 'financial-analysis',
                'tier_id' => 2,
                'description' => 'Analyzes financial statements',
                'long_description' => 'Professional financial analysis agent for statement review and insights.',
                'icon_url' => '/images/agents/financial-analysis.png',
                'capabilities' => ['Statement analysis', 'Ratio calculation', 'Trend analysis'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Marketing Campaign Agent',
                'slug' => 'marketing-campaign',
                'tier_id' => 2,
                'description' => 'Plans marketing campaigns',
                'long_description' => 'Strategic marketing campaign planner with audience targeting and channel optimization.',
                'icon_url' => '/images/agents/marketing-campaign.png',
                'capabilities' => ['Campaign planning', 'Audience targeting', 'ROI tracking'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'QA Testing Agent',
                'slug' => 'qa-testing',
                'tier_id' => 2,
                'description' => 'Tests software for bugs',
                'long_description' => 'Automated QA testing agent for bug detection and test case generation.',
                'icon_url' => '/images/agents/qa-testing.png',
                'capabilities' => ['Automated testing', 'Bug detection', 'Test reporting'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Professional Translation Agent',
                'slug' => 'pro-translation',
                'tier_id' => 2,
                'description' => 'Professional translation services',
                'long_description' => 'Advanced translation agent with context awareness and industry terminology.',
                'icon_url' => '/images/agents/pro-translation.png',
                'capabilities' => ['Context-aware translation', 'Industry terms', 'Quality assurance'],
                'supported_languages' => ['en', 'ar', 'fr', 'es', 'de'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'SEO Optimization Agent',
                'slug' => 'seo-optimization',
                'tier_id' => 2,
                'description' => 'Optimizes content for SEO',
                'long_description' => 'SEO specialist agent for keyword research and content optimization.',
                'icon_url' => '/images/agents/seo-optimization.png',
                'capabilities' => ['Keyword research', 'On-page SEO', 'Content optimization'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Customer Analytics Agent',
                'slug' => 'customer-analytics',
                'tier_id' => 2,
                'description' => 'Analyzes customer behavior',
                'long_description' => 'Customer behavior analysis agent with segmentation and insights.',
                'icon_url' => '/images/agents/customer-analytics.png',
                'capabilities' => ['Behavior analysis', 'Segmentation', 'Churn prediction'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Inventory Management Agent',
                'slug' => 'inventory-management',
                'tier_id' => 2,
                'description' => 'Manages inventory levels',
                'long_description' => 'Smart inventory management with demand forecasting and reorder automation.',
                'icon_url' => '/images/agents/inventory-management.png',
                'capabilities' => ['Stock tracking', 'Demand forecasting', 'Reorder automation'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Sales Forecasting Agent',
                'slug' => 'sales-forecasting',
                'tier_id' => 2,
                'description' => 'Forecasts sales trends',
                'long_description' => 'Sales forecasting agent with trend analysis and predictive modeling.',
                'icon_url' => '/images/agents/sales-forecasting.png',
                'capabilities' => ['Trend analysis', 'Predictive modeling', 'Revenue projection'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Report Generation Agent',
                'slug' => 'report-generation',
                'tier_id' => 2,
                'description' => 'Generates business reports',
                'long_description' => 'Automated report generation with data visualization and insights.',
                'icon_url' => '/images/agents/report-generation.png',
                'capabilities' => ['Data visualization', 'Automated reporting', 'Insights generation'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Project Planning Agent',
                'slug' => 'project-planning',
                'tier_id' => 2,
                'description' => 'Plans project timelines',
                'long_description' => 'Project planning agent with timeline creation and resource allocation.',
                'icon_url' => '/images/agents/project-planning.png',
                'capabilities' => ['Timeline creation', 'Resource allocation', 'Risk assessment'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],

            // TIER 3: Specialized Agents (15 agents) - $79/month
            [
                'name' => 'Legal Contract Review Agent',
                'slug' => 'legal-contract-review',
                'tier_id' => 3,
                'description' => 'Reviews legal contracts',
                'long_description' => 'Specialized legal agent for contract review and risk assessment.',
                'icon_url' => '/images/agents/legal-contract.png',
                'capabilities' => ['Contract analysis', 'Risk identification', 'Clause review'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'is_featured' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Medical Diagnostic Support Agent',
                'slug' => 'medical-diagnostic',
                'tier_id' => 3,
                'description' => 'Supports medical diagnostics',
                'long_description' => 'Advanced medical AI for diagnostic support and treatment recommendations.',
                'icon_url' => '/images/agents/medical-diagnostic.png',
                'capabilities' => ['Symptom analysis', 'Diagnosis support', 'Treatment suggestions'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Compliance Monitoring Agent',
                'slug' => 'compliance-monitoring',
                'tier_id' => 3,
                'description' => 'Monitors regulatory compliance',
                'long_description' => 'Regulatory compliance monitoring with automated alerts and reporting.',
                'icon_url' => '/images/agents/compliance-monitoring.png',
                'capabilities' => ['Compliance tracking', 'Regulatory updates', 'Audit preparation'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Security Analysis Agent',
                'slug' => 'security-analysis',
                'tier_id' => 3,
                'description' => 'Analyzes security vulnerabilities',
                'long_description' => 'Cybersecurity agent for vulnerability assessment and threat detection.',
                'icon_url' => '/images/agents/security-analysis.png',
                'capabilities' => ['Vulnerability scanning', 'Threat detection', 'Security audits'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Financial Regulatory Agent',
                'slug' => 'financial-regulatory',
                'tier_id' => 3,
                'description' => 'Ensures financial compliance',
                'long_description' => 'Financial regulatory compliance agent for banking and finance sectors.',
                'icon_url' => '/images/agents/financial-regulatory.png',
                'capabilities' => ['Regulatory compliance', 'AML monitoring', 'Reporting'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Architectural Design Agent',
                'slug' => 'architectural-design',
                'tier_id' => 3,
                'description' => 'Creates architectural designs',
                'long_description' => 'Specialized architectural design agent with CAD integration.',
                'icon_url' => '/images/agents/architectural-design.png',
                'capabilities' => ['Design generation', 'Code compliance', '3D modeling'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Patent Research Agent',
                'slug' => 'patent-research',
                'tier_id' => 3,
                'description' => 'Researches patent applications',
                'long_description' => 'Patent research and prior art analysis agent for IP professionals.',
                'icon_url' => '/images/agents/patent-research.png',
                'capabilities' => ['Prior art search', 'Patent analysis', 'Novelty assessment'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Forensic Accounting Agent',
                'slug' => 'forensic-accounting',
                'tier_id' => 3,
                'description' => 'Performs forensic accounting',
                'long_description' => 'Forensic accounting agent for fraud detection and financial investigation.',
                'icon_url' => '/images/agents/forensic-accounting.png',
                'capabilities' => ['Fraud detection', 'Financial investigation', 'Audit trails'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Clinical Trial Analysis Agent',
                'slug' => 'clinical-trial-analysis',
                'tier_id' => 3,
                'description' => 'Analyzes clinical trial data',
                'long_description' => 'Clinical trial data analysis with statistical modeling and reporting.',
                'icon_url' => '/images/agents/clinical-trial.png',
                'capabilities' => ['Data analysis', 'Statistical modeling', 'Trial reporting'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Real Estate Valuation Agent',
                'slug' => 'real-estate-valuation',
                'tier_id' => 3,
                'description' => 'Values real estate properties',
                'long_description' => 'Real estate valuation agent with market analysis and comparable sales.',
                'icon_url' => '/images/agents/real-estate-valuation.png',
                'capabilities' => ['Property valuation', 'Market analysis', 'Comparable sales'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Insurance Claims Agent',
                'slug' => 'insurance-claims',
                'tier_id' => 3,
                'description' => 'Processes insurance claims',
                'long_description' => 'Insurance claims processing with fraud detection and assessment.',
                'icon_url' => '/images/agents/insurance-claims.png',
                'capabilities' => ['Claims processing', 'Fraud detection', 'Risk assessment'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Supply Chain Optimization Agent',
                'slug' => 'supply-chain-optimization',
                'tier_id' => 3,
                'description' => 'Optimizes supply chains',
                'long_description' => 'Supply chain optimization with route planning and cost reduction.',
                'icon_url' => '/images/agents/supply-chain.png',
                'capabilities' => ['Route optimization', 'Cost reduction', 'Demand planning'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'M&A Due Diligence Agent',
                'slug' => 'ma-due-diligence',
                'tier_id' => 3,
                'description' => 'Conducts M&A due diligence',
                'long_description' => 'Mergers and acquisitions due diligence with risk assessment.',
                'icon_url' => '/images/agents/ma-due-diligence.png',
                'capabilities' => ['Financial analysis', 'Risk assessment', 'Document review'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Environmental Impact Agent',
                'slug' => 'environmental-impact',
                'tier_id' => 3,
                'description' => 'Assesses environmental impact',
                'long_description' => 'Environmental impact assessment with sustainability reporting.',
                'icon_url' => '/images/agents/environmental-impact.png',
                'capabilities' => ['Impact assessment', 'Sustainability reporting', 'Compliance'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Cybersecurity Audit Agent',
                'slug' => 'cybersecurity-audit',
                'tier_id' => 3,
                'description' => 'Performs security audits',
                'long_description' => 'Comprehensive cybersecurity audit with compliance checking.',
                'icon_url' => '/images/agents/cybersecurity-audit.png',
                'capabilities' => ['Security audits', 'Compliance checking', 'Penetration testing'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],

            // TIER 4: Enterprise Agents (6 agents) - $199/month
            [
                'name' => 'Custom Industry Agent',
                'slug' => 'custom-industry',
                'tier_id' => 4,
                'description' => 'Custom-trained for specific industry',
                'long_description' => 'Enterprise-grade custom agent trained for specific industry requirements.',
                'icon_url' => '/images/agents/custom-industry.png',
                'capabilities' => ['Custom training', 'Industry-specific', 'Dedicated support'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'is_featured' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Multi-lingual Legal Agent',
                'slug' => 'multilingual-legal',
                'tier_id' => 4,
                'description' => 'Legal support in 10+ languages',
                'long_description' => 'Enterprise legal agent with support for 10+ languages and jurisdictions.',
                'icon_url' => '/images/agents/multilingual-legal.png',
                'capabilities' => ['Multi-language support', 'Cross-jurisdiction', 'Legal research'],
                'supported_languages' => ['en', 'ar', 'fr', 'es', 'de', 'zh', 'ja', 'ru'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Advanced Medical AI Agent',
                'slug' => 'advanced-medical-ai',
                'tier_id' => 4,
                'description' => 'Advanced medical analysis',
                'long_description' => 'Enterprise medical AI with advanced diagnostics and treatment planning.',
                'icon_url' => '/images/agents/advanced-medical.png',
                'capabilities' => ['Advanced diagnostics', 'Treatment planning', 'Research integration'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Predictive Maintenance Agent',
                'slug' => 'predictive-maintenance',
                'tier_id' => 4,
                'description' => 'Predicts equipment failures',
                'long_description' => 'Enterprise predictive maintenance with IoT integration and failure prediction.',
                'icon_url' => '/images/agents/predictive-maintenance.png',
                'capabilities' => ['Failure prediction', 'IoT integration', 'Maintenance scheduling'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Enterprise Risk Management Agent',
                'slug' => 'enterprise-risk-management',
                'tier_id' => 4,
                'description' => 'Enterprise risk assessment',
                'long_description' => 'Comprehensive enterprise risk management with scenario modeling.',
                'icon_url' => '/images/agents/enterprise-risk.png',
                'capabilities' => ['Risk assessment', 'Scenario modeling', 'Mitigation planning'],
                'supported_languages' => ['en'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
            [
                'name' => 'Bespoke Solutions Agent',
                'slug' => 'bespoke-solutions',
                'tier_id' => 4,
                'description' => 'Custom solutions on demand',
                'long_description' => 'Fully customizable enterprise agent for bespoke business solutions.',
                'icon_url' => '/images/agents/bespoke-solutions.png',
                'capabilities' => ['Custom development', 'Integration support', 'Dedicated team'],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'runtime_type' => 'n8n',
                'is_active' => true,
                'version' => '1.0.0',
            ],
        ];

        foreach ($agents as $agent) {
            Agent::create($agent);
        }

        $this->command->info('✅ 41 agents seeded successfully!');
        $this->command->info('   - Tier 1 (Basic): 8 agents');
        $this->command->info('   - Tier 2 (Professional): 12 agents');
        $this->command->info('   - Tier 3 (Specialized): 15 agents');
        $this->command->info('   - Tier 4 (Enterprise): 6 agents');
    }
}
