<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $agents = [
            // ==================== LEGAL AGENTS ====================
            [
                'id' => Str::uuid(),
                'name' => 'LegalDoc Assistant',
                'slug' => 'legal-doc-assistant',
                'category' => 'legal',
                'description' => 'AI-powered legal document drafting and review',
                'long_description' => 'Advanced AI agent specialized in legal document creation, contract review, and compliance checking. Supports multiple jurisdictions and legal frameworks.',
                'icon_url' => '/images/agents/legal-doc.png',
                'banner_url' => '/images/agents/banners/legal-doc.jpg',
                'capabilities' => [
                    'Contract drafting',
                    'Legal document review',
                    'Compliance checking',
                    'Risk assessment',
                    'Legal research',
                ],
                'supported_languages' => ['en', 'ar', 'fr', 'es'],
                'price_model' => 'subscription',
                'base_price' => 0,
                'monthly_price' => 49.00,
                'annual_price' => 490.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => true,
                'version' => '2.1.0',
                'total_installs' => 1247,
                'rating' => 4.8,
                'review_count' => 156,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Contract Analyzer',
                'slug' => 'contract-analyzer',
                'category' => 'legal',
                'description' => 'Automated contract analysis and risk detection',
                'long_description' => 'Sophisticated AI for analyzing contracts, identifying risks, extracting key terms, and providing actionable insights.',
                'icon_url' => '/images/agents/contract-analyzer.png',
                'capabilities' => [
                    'Contract analysis',
                    'Risk detection',
                    'Key terms extraction',
                    'Clause comparison',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'free',
                'base_price' => 0,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => false,
                'version' => '1.5.2',
                'total_installs' => 892,
                'rating' => 4.6,
                'review_count' => 89,
            ],

            // ==================== MEDICAL AGENTS ====================
            [
                'id' => Str::uuid(),
                'name' => 'MedAssist Pro',
                'slug' => 'medassist-pro',
                'category' => 'medical',
                'description' => 'AI medical assistant for diagnosis support',
                'long_description' => 'Advanced medical AI supporting healthcare professionals with diagnosis suggestions, treatment plans, and medical research.',
                'icon_url' => '/images/agents/medassist.png',
                'banner_url' => '/images/agents/banners/medassist.jpg',
                'capabilities' => [
                    'Symptom analysis',
                    'Diagnosis support',
                    'Treatment recommendations',
                    'Drug interaction checking',
                    'Medical research',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'monthly_price' => 99.00,
                'annual_price' => 990.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => true,
                'version' => '3.0.1',
                'total_installs' => 2341,
                'rating' => 4.9,
                'review_count' => 312,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Patient Record Manager',
                'slug' => 'patient-record-manager',
                'category' => 'medical',
                'description' => 'Intelligent patient record organization and retrieval',
                'long_description' => 'AI-powered system for managing patient records, automating data entry, and providing quick access to medical histories.',
                'icon_url' => '/images/agents/patient-records.png',
                'capabilities' => [
                    'Record digitization',
                    'Data extraction',
                    'Quick search',
                    'Report generation',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'monthly_price' => 39.00,
                'annual_price' => 390.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => false,
                'version' => '2.3.0',
                'total_installs' => 1567,
                'rating' => 4.7,
                'review_count' => 203,
            ],

            // ==================== HR AGENTS ====================
            [
                'id' => Str::uuid(),
                'name' => 'HR Recruiter AI',
                'slug' => 'hr-recruiter-ai',
                'category' => 'hr',
                'description' => 'Intelligent recruitment and candidate screening',
                'long_description' => 'AI-powered recruitment assistant that screens resumes, schedules interviews, and identifies top candidates.',
                'icon_url' => '/images/agents/hr-recruiter.png',
                'banner_url' => '/images/agents/banners/hr-recruiter.jpg',
                'capabilities' => [
                    'Resume screening',
                    'Candidate matching',
                    'Interview scheduling',
                    'Skills assessment',
                    'Bias reduction',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'monthly_price' => 79.00,
                'annual_price' => 790.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => true,
                'version' => '2.0.0',
                'total_installs' => 1823,
                'rating' => 4.7,
                'review_count' => 267,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Employee Onboarding Assistant',
                'slug' => 'employee-onboarding',
                'category' => 'hr',
                'description' => 'Automated employee onboarding and training',
                'long_description' => 'Streamline employee onboarding with automated workflows, document management, and personalized training plans.',
                'icon_url' => '/images/agents/onboarding.png',
                'capabilities' => [
                    'Onboarding automation',
                    'Document collection',
                    'Training scheduling',
                    'Progress tracking',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'free',
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => false,
                'version' => '1.8.0',
                'total_installs' => 2145,
                'rating' => 4.5,
                'review_count' => 178,
            ],

            // ==================== FINANCE AGENTS ====================
            [
                'id' => Str::uuid(),
                'name' => 'Financial Analyst AI',
                'slug' => 'financial-analyst-ai',
                'category' => 'finance',
                'description' => 'Advanced financial analysis and forecasting',
                'long_description' => 'AI-powered financial analyst providing insights, forecasts, and investment recommendations based on market data.',
                'icon_url' => '/images/agents/financial-analyst.png',
                'banner_url' => '/images/agents/banners/financial-analyst.jpg',
                'capabilities' => [
                    'Financial modeling',
                    'Market analysis',
                    'Risk assessment',
                    'Investment recommendations',
                    'Portfolio optimization',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'monthly_price' => 149.00,
                'annual_price' => 1490.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => true,
                'version' => '2.5.0',
                'total_installs' => 987,
                'rating' => 4.8,
                'review_count' => 134,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Expense Tracker Pro',
                'slug' => 'expense-tracker-pro',
                'category' => 'finance',
                'description' => 'Automated expense tracking and reporting',
                'long_description' => 'Smart expense management system with receipt scanning, categorization, and automated reporting.',
                'icon_url' => '/images/agents/expense-tracker.png',
                'capabilities' => [
                    'Receipt scanning',
                    'Auto-categorization',
                    'Expense reports',
                    'Budget tracking',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'monthly_price' => 29.00,
                'annual_price' => 290.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => false,
                'version' => '1.9.3',
                'total_installs' => 3421,
                'rating' => 4.6,
                'review_count' => 445,
            ],

            // ==================== EDUCATION AGENTS ====================
            [
                'id' => Str::uuid(),
                'name' => 'StudyBuddy AI',
                'slug' => 'studybuddy-ai',
                'category' => 'education',
                'description' => 'Personalized learning assistant and tutor',
                'long_description' => 'AI tutor that adapts to individual learning styles, provides explanations, and creates personalized study plans.',
                'icon_url' => '/images/agents/studybuddy.png',
                'banner_url' => '/images/agents/banners/studybuddy.jpg',
                'capabilities' => [
                    'Personalized tutoring',
                    'Homework help',
                    'Study plan creation',
                    'Progress tracking',
                    'Quiz generation',
                ],
                'supported_languages' => ['en', 'ar', 'fr', 'es'],
                'price_model' => 'free',
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => true,
                'version' => '3.1.0',
                'total_installs' => 5678,
                'rating' => 4.9,
                'review_count' => 892,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Course Content Generator',
                'slug' => 'course-content-generator',
                'category' => 'education',
                'description' => 'AI-powered educational content creation',
                'long_description' => 'Create engaging course materials, lesson plans, quizzes, and presentations with AI assistance.',
                'icon_url' => '/images/agents/course-generator.png',
                'capabilities' => [
                    'Lesson planning',
                    'Quiz generation',
                    'Presentation creation',
                    'Content adaptation',
                ],
                'supported_languages' => ['en', 'ar'],
                'price_model' => 'subscription',
                'monthly_price' => 59.00,
                'annual_price' => 590.00,
                'is_marketplace' => true,
                'is_active' => true,
                'is_featured' => false,
                'version' => '2.2.1',
                'total_installs' => 1234,
                'rating' => 4.7,
                'review_count' => 156,
            ],
        ];

        foreach ($agents as $agent) {
            Agent::create($agent);
        }

        $this->command->info('✅ Agents seeded successfully!');
    }
}